version: "3.3"
services:
  redis:
    image: "redis:latest"
    ports:
    - 6379:6379
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "stats"
      POSTGRES_USER: "stats"
      POSTGRES_PASSWORD: "pgpwd4stats"
    ports:
      - "5432:5432"