apiVersion: streaming-pipeline.my.domain/v1alpha1
kind: Scaler
metadata:
  name: scaler-sample
  namespace: apps
spec:
  deployment: 
    name: consumer-deployment
    maxConsumers: 10
  brokerAddress: address
  queue: data
  period: 10m
  
  
