FROM golang:1.17
WORKDIR /go/src/github.com/valerykalashnikov/streaming-pipeline/
COPY ./ ./
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o ./bin/consumer ./cmd/consumer

FROM alpine:latest  
WORKDIR /app
COPY --from=0 /go/src/github.com/valerykalashnikov/streaming-pipeline/bin/consumer ./
ENTRYPOINT [ "./consumer" ]