FROM golang:1.17
WORKDIR /go/src/github.com/valerykalashnikov/streaming-pipeline/
COPY ./ ./
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o ./bin/file-emitter ./cmd/fileemitter

FROM alpine:latest  
WORKDIR /app
COPY --from=0 /go/src/github.com/valerykalashnikov/streaming-pipeline/bin/file-emitter ./
ENTRYPOINT [ "./file-emitter" ]