apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-deployment
spec:
  template:
    metadata:
      name: consumer-pod
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image: valerykalashnikov/consumer
        imagePullPolicy: IfNotPresent
        envFrom: 
        - configMapRef:
            name: postgres-config
        - configMapRef:
            name: redis-config
  replicas: 1
  selector:
    matchLabels:
      app: consumer